version: '3.8'

services:
  ocr-app:
    build: .
    container_name: qwen2-vl-ocr
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Flask Configuration
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8080
      - FLASK_DEBUG=False

    volumes:
      - uploads:/app/uploads

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/api/config', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads:
